version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_apteka
    restart: always
    environment:
      POSTGRES_DB: apteka
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_apteka
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data:
